FROM python:3.9.18

WORKDIR /opt/

RUN apt-get update

RUN pip install huggingface-hub llama-cpp-python

# huggingfaceからダウンロード
# RUN python download.py

# llama.cppを準備
RUN git clone https://github.com/ggerganov/llama.cpp.git
WORKDIR /opt/llama.cpp
RUN make
RUN pip install -r requirements.txt


RUN pip install llama-cpp-python