# main
FROM nvidia/cuda:12.0.0-cudnn8-devel-ubuntu20.04

ENV HOST 0.0.0.0
EXPOSE 8000

# optは動作しないので注意
WORKDIR /app

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
# 日本のミラーサイトに変更(iij)
RUN sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%http://ftp.iij.ad.jp/pub/linux/ubuntu/archive/%g" /etc/apt/sources.list

RUN apt-get update \
    && apt-get -y install cmake python3 python3-pip

ARG CMAKE_ARGS="-DLLAMA_CUBLAS=on"
ARG FORCE_CMAKE=1
RUN pip install llama-cpp-python==0.2.19
RUN pip install llama-cpp-python[server]

# サーバー起動
WORKDIR /app
COPY . /app
RUN chmod +x /app/main.sh
#CMD [ "" ]
