version: "3.0"
services:
  app:
    container_name: "r_sudo_ELYZA-japanese-Llama-2-7b"
    build:
      context: "."
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/app
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
