version: "3.0"
services:
  download:
    container_name: "LLM_server_download"
    profiles: ["download"]
    build: ./docker/download/
    volumes:
      - ./data:/data
      - ./docker/download:/download
    tty: true
  main:
    container_name: "LLM_server_main"
    profiles: ["main"]
    build: ./docker/main/
    volumes:
      - ./data:/data
      - ./docker/main:/app
    tty: true
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

