# ELYZA-japanese-Llama-2-7b-fast-instructをダウンロードする
FROM nvidia/cuda:12.0.0-cudnn8-devel-ubuntu20.04

# init
WORKDIR /opt
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN sed -i.bak -e "s%http://archive.ubuntu.com/ubuntu/%http://ftp.iij.ad.jp/pub/linux/ubuntu/archive/%g" /etc/apt/sources.list

RUN apt-get update \
    && apt-get -y install cmake git python3 python3-pip
RUN pip install huggingface-hub

# llama.cppを準備
WORKDIR /opt
RUN git clone https://github.com/ggerganov/llama.cpp.git
WORKDIR /opt/llama.cpp
RUN make LLAMA_CUBLAS=1
RUN pip install -r requirements.txt

# ダウンロード
WORKDIR /download
COPY . /download
RUN chmod +x /download/download.sh
CMD [ "bash", "/download/download.sh" ]
